### ISSUE TITLE
Not working for DEEBOT OZMO T8 AIVI 

### ISSUE THREAD

**Issue by xkuyax** [mib1185/py-sucks#3]
Hey,

thank you for making this awesome cli tool, im coming from the home assistant integration which uses this library. I tried to use `sucks --debug charge` but im getting the following response: 

[error_log.txt](https://github.com/mib1185/py-sucks/files/10472792/error_log.txt)

it appears that the connection is working (im from austria and selected AT and EU for the servers) as i got rocky 2 (the name i gave mine) in the json response.

Thank you very much for your time!

**Comment by freman** [comment]
Your error log looks very much identical to mine
[error_log.txt](https://github.com/mib1185/py-sucks/files/10474134/error_log.txt)

My bot is in Australia so have selected AU and WW

Not sure if it helps but this is sort of a request log from my android phone/app
![telegram-cloud-photo-size-5-6226660049359581705-y](https://user-images.githubusercontent.com/506680/213910607-1df20d06-94ac-4ed9-9e0f-db537afeaeea.jpg)

**Comment by dmitrym0** [comment]
Similar error for my Deebot N7:

```
❯ sucks clean 5
sleekxmppfs.basexmpp WARNING  fulljid property deprecated. Use boundjid.resource
performing clean command
Traceback (most recent call last):
  File "/Users/dmitrymarkushevich/.pyenv/versions/3.10.6/bin/sucks", line 8, in <module>
    sys.exit(cli())
  File "/Users/dmitrymarkushevich/.pyenv/versions/3.10.6/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dmitrymarkushevich/.pyenv/versions/3.10.6/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/dmitrymarkushevich/.pyenv/versions/3.10.6/lib/python3.10/site-packages/click/core.py", line 1689, in invoke
    return _process_result(rv)
  File "/Users/dmitrymarkushevich/.pyenv/versions/3.10.6/lib/python3.10/site-packages/click/core.py", line 1626, in _process_result
    value = ctx.invoke(self._result_callback, value, **ctx.params)
  File "/Users/dmitrymarkushevich/.pyenv/versions/3.10.6/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/dmitrymarkushevich/.pyenv/versions/3.10.6/lib/python3.10/site-packages/sucks/cli.py", line 219, in run
    vacbot.run(action.vac_command)
  File "/Users/dmitrymarkushevich/.pyenv/versions/3.10.6/lib/python3.10/site-packages/sucks/__init__.py", line 416, in run
    self.send_command(action.to_xml())
  File "/Users/dmitrymarkushevich/.pyenv/versions/3.10.6/lib/python3.10/site-packages/sucks/__init__.py", line 413, in send_command
    self.xmpp.send_command(xml, self._vacuum_address())
  File "/Users/dmitrymarkushevich/.pyenv/versions/3.10.6/lib/python3.10/site-packages/sucks/__init__.py", line 482, in send_command
    c.send()
  File "/Users/dmitrymarkushevich/.pyenv/versions/3.10.6/lib/python3.10/site-packages/sleekxmppfs/stanza/iq.py", line 235, in send
    raise IqError(result)
sleekxmppfs.exceptions.IqError: <iq type="error" to="ha0ujfvccd400c29@ecouser.net/7c1e73c22e4ca765a74ac2a96d8ff17a" from="6bdb36f0-eb18-419b-af69-8f662da9dd6f@r5zxjr.ecorobot.net/atom" id="f3129b89-e9dd-4b7f-a87f-86dbaa193c12-3"><error type="wait" code="404"><recipient-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" /></error></iq>
```

**Comment by xkuyax** [comment]
@dmitrym0 @freman were you able to resolve the issue somehow? With changing the country or something similar?

What app did you use to intercept those http requests on android, i would like to try that as well :D

**Comment by dmitrym0** [comment]
> @dmitrym0 @freman were you able to resolve the issue somehow? With changing the country or something similar?
> 
> What app did you use to intercept those http requests on android, i would like to try that as well :D

I have not, the suggestion seems to be related to the continent, I tried that. No go.

**Comment by freman** [comment]
I have also not been able to solve it.

**Comment by albatrossflavour** [comment]
+1

**Comment by amcolex** [comment]
+1 here as well DEEBOT OZMO T8 AIVI in Switzerland.

**Comment by Tecleck** [comment]
+1 DEEBOX X1 OMNI in the Netherlands, also tried continent ww instead of eu , no luck. 
Same errors: 

sucks      DEBUG    *** sending ping ***
sucks      WARNING  Ping did not reach VacBot. Will retry.
sucks      DEBUG    *** Error type: wait
sucks      DEBUG    *** Error condition: recipient-unavailable
sucks      DEBUG    *** sending ping ***
